In [1]:
import pandas as pd

## Add Batch Information

In [2]:
manifest_final = pd.read_csv('/Users/vivianschu/repos/pmlb-organoids/metadata/260313_manifest_final.tsv', sep='\t')
manifest_final

,sample,read1,read2,source_sample_names
0,BPTO0051.TPO,/cluster/projects/livingbank/workspace/vivian/...,/cluster/projects/livingbank/workspace/vivian/...,BPTO0051.TPO
1,BPTO0064.TXO,/cluster/projects/livingbank/workspace/vivian/...,/cluster/projects/livingbank/workspace/vivian/...,BPTO0064.TXO
2,BPTO0093.TPO,/cluster/projects/livingbank/workspace/vivian/...,/cluster/projects/livingbank/workspace/vivian/...,BPTO0093.TPO
3,BPTO0095.TPO,/cluster/projects/livingbank/workspace/vivian/...,/cluster/projects/livingbank/workspace/vivian/...,BPTO0095.TPO
4,BPTO0143.TXO,/cluster/projects/livingbank/workspace/vivian/...,/cluster/projects/livingbank/workspace/vivian/...,BPTO0143.TXO
...,...,...,...,...
227,SGPC0007.TXO_pmlb,/cluster/projects/livingbank/workspace/vivian/...,/cluster/projects/livingbank/workspace/vivian/...,"SGPC0007.TXO_A,SGPC0007.TXO_B"
228,SGPC0023.TXO_pmlb,/cluster/projects/livingbank/workspace/vivian/...,/cluster/projects/livingbank/workspace/vivian/...,"SGPC0023.TXO_A,SGPC0023.TXO_B"
229,SGPC0031.TXO,/cluster/projects/livingbank/workspace/vivian/...,/cluster/projects/livingbank/workspace/vivian/...,SGPC0031.TXO
230,SGPC0035.TXO,/cluster/projects/livingbank/workspace/vivian/...,/cluster/projects/livingbank/workspace/vivian/...,SGPC0035.TXO
231,SGPC0058.TXO_pmlb,/cluster/projects/livingbank/workspace/vivian/...,/cluster/projects/livingbank/workspace/vivian/...,"SGPC0058.TXO_A,SGPC0058.TXO_B"

In [3]:
manifest_replicate = pd.read_csv('/Users/vivianschu/repos/pmlb-organoids/metadata/260225_manifest_replicates.csv')
manifest_replicate

,sample_name,group_name,mate1,mate2
0,BPTO0051.TPO,NaN,/cluster/projects/livingbank/Data/RNAseq/Cesco...,/cluster/projects/livingbank/Data/RNAseq/Cesco...
1,BPTO0064.TXO,NaN,/cluster/projects/livingbank/Data/RNAseq/Cesco...,/cluster/projects/livingbank/Data/RNAseq/Cesco...
2,BPTO0093.TPO,NaN,/cluster/projects/livingbank/Data/RNAseq/RNAse...,/cluster/projects/livingbank/Data/RNAseq/RNAse...
3,BPTO0095.TPO,NaN,/cluster/projects/livingbank/Data/RNAseq/Cesco...,/cluster/projects/livingbank/Data/RNAseq/Cesco...
4,BPTO0143.TXO,NaN,/cluster/projects/livingbank/Data/RNAseq/RNAse...,/cluster/projects/livingbank/Data/RNAseq/RNAse...
...,...,...,...,...
306,SGPC0023.TXO_B,SGPC0023.TXO_pmlb,/cluster/projects/livingbank/Data/RNAseq/PMLB/...,/cluster/projects/livingbank/Data/RNAseq/PMLB/...
307,SGPC0031.TXO,NaN,/cluster/projects/livingbank/Data/RNAseq/RNAse...,/cluster/projects/livingbank/Data/RNAseq/RNAse...
308,SGPC0035.TXO,NaN,/cluster/projects/livingbank/Data/RNAseq/RNAse...,/cluster/projects/livingbank/Data/RNAseq/RNAse...
309,SGPC0058.TXO_A,SGPC0058.TXO_pmlb,/cluster/projects/livingbank/Data/RNAseq/PMLB/...,/cluster/projects/livingbank/Data/RNAseq/PMLB/...
310,SGPC0058.TXO_B,SGPC0058.TXO_pmlb,/cluster/projects/livingbank/Data/RNAseq/PMLB/...,/cluster/projects/livingbank/Data/RNAseq/PMLB/...

In [4]:
# final_sample_name to combine sample_name and group_name, keep group_name if it exists instead
def combine_sample_group(row):
    if pd.notna(row['group_name']):
        return row['group_name']
    else:
        return row['sample_name']

manifest_replicate['final_sample_name'] = manifest_replicate.apply(combine_sample_group, axis=1)
manifest_replicate

,sample_name,group_name,mate1,mate2,final_sample_name
0,BPTO0051.TPO,NaN,/cluster/projects/livingbank/Data/RNAseq/Cesco...,/cluster/projects/livingbank/Data/RNAseq/Cesco...,BPTO0051.TPO
1,BPTO0064.TXO,NaN,/cluster/projects/livingbank/Data/RNAseq/Cesco...,/cluster/projects/livingbank/Data/RNAseq/Cesco...,BPTO0064.TXO
2,BPTO0093.TPO,NaN,/cluster/projects/livingbank/Data/RNAseq/RNAse...,/cluster/projects/livingbank/Data/RNAseq/RNAse...,BPTO0093.TPO
3,BPTO0095.TPO,NaN,/cluster/projects/livingbank/Data/RNAseq/Cesco...,/cluster/projects/livingbank/Data/RNAseq/Cesco...,BPTO0095.TPO
4,BPTO0143.TXO,NaN,/cluster/projects/livingbank/Data/RNAseq/RNAse...,/cluster/projects/livingbank/Data/RNAseq/RNAse...,BPTO0143.TXO
...,...,...,...,...,...
306,SGPC0023.TXO_B,SGPC0023.TXO_pmlb,/cluster/projects/livingbank/Data/RNAseq/PMLB/...,/cluster/projects/livingbank/Data/RNAseq/PMLB/...,SGPC0023.TXO_pmlb
307,SGPC0031.TXO,NaN,/cluster/projects/livingbank/Data/RNAseq/RNAse...,/cluster/projects/livingbank/Data/RNAseq/RNAse...,SGPC0031.TXO
308,SGPC0035.TXO,NaN,/cluster/projects/livingbank/Data/RNAseq/RNAse...,/cluster/projects/livingbank/Data/RNAseq/RNAse...,SGPC0035.TXO
309,SGPC0058.TXO_A,SGPC0058.TXO_pmlb,/cluster/projects/livingbank/Data/RNAseq/PMLB/...,/cluster/projects/livingbank/Data/RNAseq/PMLB/...,SGPC0058.TXO_pmlb
310,SGPC0058.TXO_B,SGPC0058.TXO_pmlb,/cluster/projects/livingbank/Data/RNAseq/PMLB/...,/cluster/projects/livingbank/Data/RNAseq/PMLB/...,SGPC0058.TXO_pmlb

In [5]:
# add column indicating the folder origin, after /cluster/projects/livingbank/Data/RNAseq/
def extract_folder(path):
    key = '/cluster/projects/livingbank/Data/RNAseq/'
    if key in path:
        parts = path.split(key)[1].split('/')
        if parts[0] == 'RNAseq_Niki_Novogene' and len(parts) > 1:
            return f"{parts[0]}/{parts[1]}"
        else:
            return parts[0]
    else:
        return None


manifest_replicate['batch'] = manifest_replicate['mate1'].apply(extract_folder)
manifest_replicate

,sample_name,group_name,mate1,mate2,final_sample_name,batch
0,BPTO0051.TPO,NaN,/cluster/projects/livingbank/Data/RNAseq/Cesco...,/cluster/projects/livingbank/Data/RNAseq/Cesco...,BPTO0051.TPO,Cescon_lab
1,BPTO0064.TXO,NaN,/cluster/projects/livingbank/Data/RNAseq/Cesco...,/cluster/projects/livingbank/Data/RNAseq/Cesco...,BPTO0064.TXO,Cescon_lab
2,BPTO0093.TPO,NaN,/cluster/projects/livingbank/Data/RNAseq/RNAse...,/cluster/projects/livingbank/Data/RNAseq/RNAse...,BPTO0093.TPO,RNAseq_Niki_Novogene/X202SC22083755-Z01-F001
3,BPTO0095.TPO,NaN,/cluster/projects/livingbank/Data/RNAseq/Cesco...,/cluster/projects/livingbank/Data/RNAseq/Cesco...,BPTO0095.TPO,Cescon_lab
4,BPTO0143.TXO,NaN,/cluster/projects/livingbank/Data/RNAseq/RNAse...,/cluster/projects/livingbank/Data/RNAseq/RNAse...,BPTO0143.TXO,RNAseq_Niki_Novogene/X202SC22083755-Z01-F001
...,...,...,...,...,...,...
306,SGPC0023.TXO_B,SGPC0023.TXO_pmlb,/cluster/projects/livingbank/Data/RNAseq/PMLB/...,/cluster/projects/livingbank/Data/RNAseq/PMLB/...,SGPC0023.TXO_pmlb,PMLB
307,SGPC0031.TXO,NaN,/cluster/projects/livingbank/Data/RNAseq/RNAse...,/cluster/projects/livingbank/Data/RNAseq/RNAse...,SGPC0031.TXO,RNAseq_Niki_Novogene/X202SC22083755-Z01-F001
308,SGPC0035.TXO,NaN,/cluster/projects/livingbank/Data/RNAseq/RNAse...,/cluster/projects/livingbank/Data/RNAseq/RNAse...,SGPC0035.TXO,RNAseq_Niki_Novogene/X202SC22083755-Z01-F001
309,SGPC0058.TXO_A,SGPC0058.TXO_pmlb,/cluster/projects/livingbank/Data/RNAseq/PMLB/...,/cluster/projects/livingbank/Data/RNAseq/PMLB/...,SGPC0058.TXO_pmlb,PMLB
310,SGPC0058.TXO_B,SGPC0058.TXO_pmlb,/cluster/projects/livingbank/Data/RNAseq/PMLB/...,/cluster/projects/livingbank/Data/RNAseq/PMLB/...,SGPC0058.TXO_pmlb,PMLB

In [6]:
# map manifest_replicate['batch'] to manifest using 'final_sample_name' and 'sample'
batch_mapping = manifest_replicate.set_index('final_sample_name')['batch'].to_dict()
manifest_final['batch'] = manifest_final['sample'].map(batch_mapping)

# also add mate1 and mate2 for historical
mate1_mapping = manifest_replicate.set_index('final_sample_name')['mate1'].to_dict()
mate2_mapping = manifest_replicate.set_index('final_sample_name')['mate2'].to_dict()
manifest_final['mate1'] = manifest_final['sample'].map(mate1_mapping)
manifest_final['mate2'] = manifest_final['sample'].map(mate2_mapping)
manifest_final

,sample,read1,read2,source_sample_names,batch,mate1,mate2
0,BPTO0051.TPO,/cluster/projects/livingbank/workspace/vivian/...,/cluster/projects/livingbank/workspace/vivian/...,BPTO0051.TPO,Cescon_lab,/cluster/projects/livingbank/Data/RNAseq/Cesco...,/cluster/projects/livingbank/Data/RNAseq/Cesco...
1,BPTO0064.TXO,/cluster/projects/livingbank/workspace/vivian/...,/cluster/projects/livingbank/workspace/vivian/...,BPTO0064.TXO,Cescon_lab,/cluster/projects/livingbank/Data/RNAseq/Cesco...,/cluster/projects/livingbank/Data/RNAseq/Cesco...
2,BPTO0093.TPO,/cluster/projects/livingbank/workspace/vivian/...,/cluster/projects/livingbank/workspace/vivian/...,BPTO0093.TPO,RNAseq_Niki_Novogene/X202SC22083755-Z01-F001,/cluster/projects/livingbank/Data/RNAseq/RNAse...,/cluster/projects/livingbank/Data/RNAseq/RNAse...
3,BPTO0095.TPO,/cluster/projects/livingbank/workspace/vivian/...,/cluster/projects/livingbank/workspace/vivian/...,BPTO0095.TPO,Cescon_lab,/cluster/projects/livingbank/Data/RNAseq/Cesco...,/cluster/projects/livingbank/Data/RNAseq/Cesco...
4,BPTO0143.TXO,/cluster/projects/livingbank/workspace/vivian/...,/cluster/projects/livingbank/workspace/vivian/...,BPTO0143.TXO,RNAseq_Niki_Novogene/X202SC22083755-Z01-F001,/cluster/projects/livingbank/Data/RNAseq/RNAse...,/cluster/projects/livingbank/Data/RNAseq/RNAse...
...,...,...,...,...,...,...,...
227,SGPC0007.TXO_pmlb,/cluster/projects/livingbank/workspace/vivian/...,/cluster/projects/livingbank/workspace/vivian/...,"SGPC0007.TXO_A,SGPC0007.TXO_B",PMLB,/cluster/projects/livingbank/Data/RNAseq/PMLB/...,/cluster/projects/livingbank/Data/RNAseq/PMLB/...
228,SGPC0023.TXO_pmlb,/cluster/projects/livingbank/workspace/vivian/...,/cluster/projects/livingbank/workspace/vivian/...,"SGPC0023.TXO_A,SGPC0023.TXO_B",PMLB,/cluster/projects/livingbank/Data/RNAseq/PMLB/...,/cluster/projects/livingbank/Data/RNAseq/PMLB/...
229,SGPC0031.TXO,/cluster/projects/livingbank/workspace/vivian/...,/cluster/projects/livingbank/workspace/vivian/...,SGPC0031.TXO,RNAseq_Niki_Novogene/X202SC22083755-Z01-F001,/cluster/projects/livingbank/Data/RNAseq/RNAse...,/cluster/projects/livingbank/Data/RNAseq/RNAse...
230,SGPC0035.TXO,/cluster/projects/livingbank/workspace/vivian/...,/cluster/projects/livingbank/workspace/vivian/...,SGPC0035.TXO,RNAseq_Niki_Novogene/X202SC22083755-Z01-F001,/cluster/projects/livingbank/Data/RNAseq/RNAse...,/cluster/projects/livingbank/Data/RNAseq/RNAse...
231,SGPC0058.TXO_pmlb,/cluster/projects/livingbank/workspace/vivian/...,/cluster/projects/livingbank/workspace/vivian/...,"SGPC0058.TXO_A,SGPC0058.TXO_B",PMLB,/cluster/projects/livingbank/Data/RNAseq/PMLB/...,/cluster/projects/livingbank/Data/RNAseq/PMLB/...

In [7]:
# which manifest['batch'] are NaN?
nan_batches = manifest_final[manifest_final['batch'].isna()]['sample']
print(nan_batches)
print(len(nan_batches))

Series([], Name: sample, dtype: object)
0

In [8]:
# Folder distribution
manifest_final['batch'].value_counts()

batch
RNAseq_Niki_Novogene/X202SC22083755-Z01-F001     43
PMLB                                             42
RNAseq_Niki_Novogene/X202SC22121835-Z01-F001     35
RNAseq_Niki_Novogene/X202SC23022077-Z01-F001     21
RNAseq_Niki_Novogene/X202SC23051771-Z01-F001     17
From_Yong_2025_08                                11
Before_2019                                      10
RNAseq_Niki_Novogene/X202SC23012282-Z01-F004     10
RNAseq_Niki_Novogene/X202SC23012282-Z01-F001      8
RNAseq_Niki_Novogene/X202SC22121835-Z01-F002      7
RNAseq_Niki_Novogene/X202SC23012282-Z01-F003      6
RNAseq_Niki_Novogene/X202SC23012282-Z01-F002      6
RNAseq_Niki_Novogene/X202SC25057089-Z01-F001      4
230403_A00784_0686_BHW7HHDRX2_Tsao220511          4
230317_A00827_0775_BHV2JWDSX5_Lheureux_220310     3
Cescon_lab                                        3
RNAseq_Niki_Novogene/X202SC24030464-Z01-F001      2
Name: count, dtype: int64

In [9]:
# export csv as sample_manifest.tsv
manifest_final.to_csv('/Users/vivianschu/repos/pmlb-organoids/metadata/260313_manifest_batch.tsv', sep='\t', index=False)

## Clean Metadata

In [10]:
# load gene tpm data
gene_tpm = pd.read_csv('/Users/vivianschu/repos/pmlb-organoids/data/combined_TPM.txt', sep='\t', index_col=0)
print(gene_tpm.shape)

# load star data
star_df = pd.read_csv('/Users/vivianschu/repos/pmlb-organoids/data/star_mapping_stats.tsv', sep='\t')
# load metadata
metadata_df = pd.read_csv('/Users/vivianschu/repos/pmlb-organoids/metadata/PMLB_LongTermTumor_Organoid_20260107.csv')
# remove unnamed col
metadata_df = metadata_df.loc[:, ~metadata_df.columns.str.contains('^Unnamed')]

# in new df, create col sample from gene_tpm columns except for first column
metadata = pd.DataFrame({'sample': gene_tpm.columns})
metadata.head()

(58037, 232)

         sample
0  BPTO0051.TPO
1  BPTO0064.TXO
2  BPTO0093.TPO
3  BPTO0095.TPO
4  BPTO0143.TXO

In [11]:
# map sample to PMLB_organoidID in metadata_df to get batch info
# if NaN, strip chars after '_' from sample name and try again
def map_to_organoid_id(sample_name):
    if sample_name in metadata_df['PMLB_organoidID'].values:
        return sample_name
    else:
        stripped_name = sample_name.split('_')[0]
        if stripped_name in metadata_df['PMLB_organoidID'].values:
            return stripped_name
        else:
            return None

metadata['PMLB_organoidID'] = metadata['sample'].apply(map_to_organoid_id)

metadata

                sample PMLB_organoidID
0         BPTO0051.TPO    BPTO0051.TPO
1         BPTO0064.TXO    BPTO0064.TXO
2         BPTO0093.TPO    BPTO0093.TPO
3         BPTO0095.TPO    BPTO0095.TPO
4         BPTO0143.TXO    BPTO0143.TXO
..                 ...             ...
227  SGPC0007.TXO_pmlb    SGPC0007.TXO
228  SGPC0023.TXO_pmlb    SGPC0023.TXO
229       SGPC0031.TXO    SGPC0031.TXO
230       SGPC0035.TXO    SGPC0035.TXO
231  SGPC0058.TXO_pmlb    SGPC0058.TXO

[232 rows x 2 columns]

In [12]:
# add columns 'PMLB_organoidID', cancer_type, 'oncotree_code', 'primary_tumor_site', 'organoid_sample_class',  from metadata_df
metadata = metadata.merge(metadata_df[['PMLB_organoidID', 'cancer_type', 'oncotree_code', 'primary_tumor_site', 'organoid_sample_class']], left_on='PMLB_organoidID', right_on='PMLB_organoidID', how='left')

# remove the word ' Cancer' from cancer_type
metadata['cancer_type'] = metadata['cancer_type'].str.replace(' Cancer', '', regex=False)
metadata

,sample,PMLB_organoidID,cancer_type,oncotree_code,primary_tumor_site,organoid_sample_class
0,BPTO0051.TPO,BPTO0051.TPO,Breast,BRCA,Breast,PO
1,BPTO0064.TXO,BPTO0064.TXO,Breast,BRCA,Breast,XO
2,BPTO0093.TPO,BPTO0093.TPO,Breast,BRCA,Breast,PO
3,BPTO0095.TPO,BPTO0095.TPO,Breast,BRCA,Breast,PO
4,BPTO0143.TXO,BPTO0143.TXO,Breast,BRCA,Breast,XO
...,...,...,...,...,...,...
227,SGPC0007.TXO_pmlb,SGPC0007.TXO,Pancreatic,PAAD,Pancreas,XO
228,SGPC0023.TXO_pmlb,SGPC0023.TXO,Pancreatic,PAAD,Pancreas,XO
229,SGPC0031.TXO,SGPC0031.TXO,Pancreatic,PAAD,Pancreas,XO
230,SGPC0035.TXO,SGPC0035.TXO,Pancreatic,PAAD,Pancreas,XO
231,SGPC0058.TXO_pmlb,SGPC0058.TXO,Pancreatic,PAAD,Pancreas,XO

In [13]:
# combine manifest['batch'] and metadata
metadata = metadata.merge(manifest_final[['sample', 'batch']], left_on='sample', right_on='sample', how='left')

# export as metadata.to_csv
metadata.to_csv('/Users/vivianschu/repos/pmlb-organoids/metadata/metadata.csv', index=False)
metadata.head()

,sample,PMLB_organoidID,cancer_type,oncotree_code,primary_tumor_site,organoid_sample_class,batch
0,BPTO0051.TPO,BPTO0051.TPO,Breast,BRCA,Breast,PO,Cescon_lab
1,BPTO0064.TXO,BPTO0064.TXO,Breast,BRCA,Breast,XO,Cescon_lab
2,BPTO0093.TPO,BPTO0093.TPO,Breast,BRCA,Breast,PO,RNAseq_Niki_Novogene/X202SC22083755-Z01-F001
3,BPTO0095.TPO,BPTO0095.TPO,Breast,BRCA,Breast,PO,Cescon_lab
4,BPTO0143.TXO,BPTO0143.TXO,Breast,BRCA,Breast,XO,RNAseq_Niki_Novogene/X202SC22083755-Z01-F001